# Generated by Django 6.0.3 on 2026-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0002_linkedinprofile_self_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
