# Generated by Django 6.0.3 on 2026-04-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0003_campaign_active'),
        ('linkedin', '0003_siteconfig'),
    ]

    operations = [
    ]
