# Generated by Django 6.0.3 on 2026-04-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0004_merge_0003_campaign_active_0003_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('send_message', 'Send Message'), ('check_inbox', 'Check Inbox')], max_length=30),
        ),
    ]
