# Generated by Django 6.0.3 on 2026-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0006_account_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='claimed_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='proxy_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
