# Generated by Django 6.0.3 on 2026-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0008_account_pool_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='inbox_bootstrap_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_inbox_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
